// Generated by Wrangler — do not edit manually
// Run `npm run cf-typegen` to regenerate after wrangler.toml changes

interface Env {
  DB: D1Database;
  RATE_LIMIT_KV: KVNamespace;
  ASSETS: Fetcher;
  ADMIN_USERNAME: string;
  ADMIN_PASSWORD: string;
  JWT_SECRET: string;
}

